# Generated by Django 3.0.5 on 2021-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(default=None, max_length=100)),
                ('emp_first_name', models.CharField(default=None, max_length=100)),
                ('emp_location', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
