# Generated by Django 3.0.5 on 2021-01-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='emp_first_name',
            new_name='employee_name',
        ),
    ]
